[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "matplotlib-venn>=1.1.2",
    "streamlit>=1.49.1",
]
